# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_college.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCollegeWidget(object):
    def setupUi(self, AddCollegeWidget):
        AddCollegeWidget.setObjectName("AddCollegeWidget")
        AddCollegeWidget.resize(800, 480)
        self.college_name_label = QtWidgets.QLabel(AddCollegeWidget)
        self.college_name_label.setGeometry(QtCore.QRect(160, 110, 240, 40))
        self.college_name_label.setObjectName("college_name_label")
        self.college_id_label = QtWidgets.QLabel(AddCollegeWidget)
        self.college_id_label.setGeometry(QtCore.QRect(160, 190, 240, 40))
        self.college_id_label.setObjectName("college_id_label")
        self.college_name_edit = QtWidgets.QLineEdit(AddCollegeWidget)
        self.college_name_edit.setGeometry(QtCore.QRect(400, 110, 240, 40))
        self.college_name_edit.setObjectName("college_name_edit")
        self.college_id_edit = QtWidgets.QLineEdit(AddCollegeWidget)
        self.college_id_edit.setGeometry(QtCore.QRect(400, 190, 240, 40))
        self.college_id_edit.setObjectName("college_id_edit")
        self.accept_button = QtWidgets.QPushButton(AddCollegeWidget)
        self.accept_button.setGeometry(QtCore.QRect(280, 320, 240, 40))
        self.accept_button.setObjectName("accept_button")

        self.retranslateUi(AddCollegeWidget)
        QtCore.QMetaObject.connectSlotsByName(AddCollegeWidget)

    def retranslateUi(self, AddCollegeWidget):
        _translate = QtCore.QCoreApplication.translate
        AddCollegeWidget.setWindowTitle(_translate("AddCollegeWidget", "添加院系"))
        self.college_name_label.setText(_translate("AddCollegeWidget", "院系名"))
        self.college_id_label.setText(_translate("AddCollegeWidget", "院系号"))
        self.accept_button.setText(_translate("AddCollegeWidget", "添加"))
