# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_college.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCollegeWidget(object):
    def setupUi(self, AddCollegeWidget):
        AddCollegeWidget.setObjectName("AddCollegeWidget")
        AddCollegeWidget.resize(800, 480)
        self.college_name_label = QtWidgets.QLabel(AddCollegeWidget)
        self.college_name_label.setGeometry(QtCore.QRect(160, 110, 240, 40))
        self.college_name_label.setObjectName("college_name_label")
        self.college_id_label = QtWidgets.QLabel(AddCollegeWidget)
        self.college_id_label.setGeometry(QtCore.QRect(160, 190, 240, 40))
        self.college_id_label.setObjectName("college_id_label")
        self.college_name_edit = QtWidgets.QLineEdit(AddCollegeWidget)
        self.college_name_edit.setGeometry(QtCore.QRect(400, 110, 240, 40))
        self.college_name_edit.setObjectName("college_name_edit")
        self.college_id_edit = QtWidgets.QLineEdit(AddCollegeWidget)
        self.college_id_edit.setGeometry(QtCore.QRect(400, 190, 240, 40))
        self.college_id_edit.setObjectName("college_id_edit")

        self.accept_button = QtWidgets.QPushButton(AddCollegeWidget)
        self.accept_button.setGeometry(QtCore.QRect(280, 320, 240, 40))
        self.accept_button.setObjectName("accept_button")
        self.accept_button.clicked.connect(self._add_college)

        self.retranslateUi(AddCollegeWidget)
        QtCore.QMetaObject.connectSlotsByName(AddCollegeWidget)
        self.widget = AddCollegeWidget

    def retranslateUi(self, AddCollegeWidget):
        _translate = QtCore.QCoreApplication.translate
        AddCollegeWidget.setWindowTitle(_translate("AddCollegeWidget", "添加院系"))
        self.college_name_label.setText(_translate("AddCollegeWidget", "院系名"))
        self.college_id_label.setText(_translate("AddCollegeWidget", "院系号"))
        self.accept_button.setText(_translate("AddCollegeWidget", "添加"))

    def _add_college(self):
        database = sqlite3.connect('Database_System/Lab1/data/data.db')

        college_name = self.college_name_edit.text()
        college_id = self.college_id_edit.text()
        if college_id.isnumeric() == False:
            QtWidgets.QMessageBox.warning(self.widget, '警告', '院系号必须为纯数字')
            return
        college_id = int(college_id)

        exist_id = database.execute('SELECT id FROM COLLEGE')
        for row in exist_id:
            if row[0] == college_id:
                QtWidgets.QMessageBox.warning(self.widget, '警告', '院系号已存在')
                return

        command = 'INSERT INTO COLLEGE VALUES (%d, \'%s\')' % (college_id,
                                                               college_name)
        database.execute(command)

        QtWidgets.QMessageBox.information(self.widget, '提示', '添加成功')
        database.execute('COMMIT;')
        database.close()
