# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_course.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCourseWidget(object):
    def setupUi(self, AddCourseWidget):
        AddCourseWidget.setObjectName("AddCourseWidget")
        AddCourseWidget.resize(800, 480)
        self.course_name_label = QtWidgets.QLabel(AddCourseWidget)
        self.course_name_label.setGeometry(QtCore.QRect(160, 70, 240, 40))
        self.course_name_label.setObjectName("course_name_label")
        self.course_id_label = QtWidgets.QLabel(AddCourseWidget)
        self.course_id_label.setGeometry(QtCore.QRect(160, 150, 240, 40))
        self.course_id_label.setObjectName("course_id_label")
        self.course_name_edit = QtWidgets.QLineEdit(AddCourseWidget)
        self.course_name_edit.setGeometry(QtCore.QRect(400, 70, 240, 40))
        self.course_name_edit.setObjectName("course_name_edit")
        self.course_id_edit = QtWidgets.QLineEdit(AddCourseWidget)
        self.course_id_edit.setGeometry(QtCore.QRect(400, 150, 240, 40))
        self.course_id_edit.setObjectName("course_id_edit")
        self.accept_button = QtWidgets.QPushButton(AddCourseWidget)
        self.accept_button.setGeometry(QtCore.QRect(280, 400, 240, 40))
        self.accept_button.setObjectName("accept_button")
        self.teacher_label = QtWidgets.QLabel(AddCourseWidget)
        self.teacher_label.setGeometry(QtCore.QRect(160, 230, 240, 40))
        self.teacher_label.setObjectName("teacher_label")
        self.teacher_box = QtWidgets.QComboBox(AddCourseWidget)
        self.teacher_box.setGeometry(QtCore.QRect(400, 230, 240, 40))
        self.teacher_box.setObjectName("teacher_box")
        self.college_box = QtWidgets.QComboBox(AddCourseWidget)
        self.college_box.setGeometry(QtCore.QRect(400, 310, 240, 40))
        self.college_box.setObjectName("college_box")
        self.college_label = QtWidgets.QLabel(AddCourseWidget)
        self.college_label.setGeometry(QtCore.QRect(160, 310, 240, 40))
        self.college_label.setObjectName("college_label")

        self.retranslateUi(AddCourseWidget)
        QtCore.QMetaObject.connectSlotsByName(AddCourseWidget)

    def retranslateUi(self, AddCourseWidget):
        _translate = QtCore.QCoreApplication.translate
        AddCourseWidget.setWindowTitle(_translate("AddCourseWidget", "添加课程"))
        self.course_name_label.setText(_translate("AddCourseWidget", "课程名称"))
        self.course_id_label.setText(_translate("AddCourseWidget", "课程号"))
        self.accept_button.setText(_translate("AddCourseWidget", "添加"))
        self.teacher_label.setText(_translate("AddCourseWidget", "授课教师"))
        self.college_label.setText(_translate("AddCourseWidget", "所属院系"))
