# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_course.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCourseWidget(object):
    def setupUi(self, AddCourseWidget):
        AddCourseWidget.setObjectName("AddCourseWidget")
        AddCourseWidget.resize(800, 480)
        self.course_name_label = QtWidgets.QLabel(AddCourseWidget)
        self.course_name_label.setGeometry(QtCore.QRect(160, 70, 240, 40))
        self.course_name_label.setObjectName("course_name_label")
        self.course_id_label = QtWidgets.QLabel(AddCourseWidget)
        self.course_id_label.setGeometry(QtCore.QRect(160, 150, 240, 40))
        self.course_id_label.setObjectName("course_id_label")
        self.course_name_edit = QtWidgets.QLineEdit(AddCourseWidget)
        self.course_name_edit.setGeometry(QtCore.QRect(400, 70, 240, 40))
        self.course_name_edit.setObjectName("course_name_edit")
        self.course_id_edit = QtWidgets.QLineEdit(AddCourseWidget)
        self.course_id_edit.setGeometry(QtCore.QRect(400, 150, 240, 40))
        self.course_id_edit.setObjectName("course_id_edit")
        self.teacher_label = QtWidgets.QLabel(AddCourseWidget)
        self.teacher_label.setGeometry(QtCore.QRect(160, 230, 240, 40))
        self.teacher_label.setObjectName("teacher_label")

        database = sqlite3.connect('Database_System/Lab1/data/data.db')

        self.teacher_box = QtWidgets.QComboBox(AddCourseWidget)
        self.teacher_box.setGeometry(QtCore.QRect(400, 230, 240, 40))
        self.teacher_box.setObjectName("teacher_box")
        teachers = database.execute('SELECT name, id FROM TEACHER ORDER BY id')
        teachers = [row[0] + ' ' + str(row[1]) for row in teachers]
        self.teacher_box.addItems(teachers)

        self.college_box = QtWidgets.QComboBox(AddCourseWidget)
        self.college_box.setGeometry(QtCore.QRect(400, 310, 240, 40))
        self.college_box.setObjectName("college_box")
        colleges = database.execute('SELECT name, id FROM COLLEGE ORDER BY id')
        colleges = [row[0] + ' ' + str(row[1]) for row in colleges]
        self.college_box.addItems(colleges)

        self.college_label = QtWidgets.QLabel(AddCourseWidget)
        self.college_label.setGeometry(QtCore.QRect(160, 310, 240, 40))
        self.college_label.setObjectName("college_label")

        self.accept_button = QtWidgets.QPushButton(AddCourseWidget)
        self.accept_button.setGeometry(QtCore.QRect(280, 400, 240, 40))
        self.accept_button.setObjectName("accept_button")
        self.accept_button.clicked.connect(self._add_course)

        self.retranslateUi(AddCourseWidget)
        QtCore.QMetaObject.connectSlotsByName(AddCourseWidget)
        self.widget = AddCourseWidget

    def retranslateUi(self, AddCourseWidget):
        _translate = QtCore.QCoreApplication.translate
        AddCourseWidget.setWindowTitle(_translate("AddCourseWidget", "添加课程"))
        self.course_name_label.setText(_translate("AddCourseWidget", "课程名称"))
        self.course_id_label.setText(_translate("AddCourseWidget", "课程号"))
        self.accept_button.setText(_translate("AddCourseWidget", "添加"))
        self.teacher_label.setText(_translate("AddCourseWidget", "授课教师"))
        self.college_label.setText(_translate("AddCourseWidget", "所属院系"))

    def _add_course(self):
        database = sqlite3.connect('Database_System/Lab1/data/data.db')

        course_name = self.course_name_edit.text()
        course_id = self.course_id_edit.text()
        if course_id.isnumeric() == False:
            QtWidgets.QMessageBox.warning(self.widget, '警告', '课号必须为纯数字')
            return
        course_id = int(course_id)

        exist_id = database.execute('SELECT id FROM COURSE')
        for row in exist_id:
            if row[0] == course_id:
                QtWidgets.QMessageBox.warning(self.widget, '警告', '该课号已存在')
                return

        teacher_id = int((self.teacher_box.currentText().split())[1])
        college_id = int((self.college_box.currentText().split())[1])

        command = 'INSERT INTO COURSE VALUES (%d, \'%s\', %d, %d)' % (
            course_id, course_name, teacher_id, college_id)
        database.execute(command)

        QtWidgets.QMessageBox.information(self.widget, '提示', '添加成功')
        database.execute('COMMIT;')
        database.close()
