# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.add_college_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_college_button.setGeometry(QtCore.QRect(280, 50, 240, 40))
        self.add_college_button.setObjectName("add_college_button")

        self.add_teacher_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_teacher_button.setGeometry(QtCore.QRect(280, 130, 240, 40))
        self.add_teacher_button.setObjectName("add_teacher_button")

        self.add_student_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_student_button.setGeometry(QtCore.QRect(280, 210, 240, 40))
        self.add_student_button.setObjectName("add_student_button")

        self.add_course_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_course_button.setGeometry(QtCore.QRect(280, 290, 240, 40))
        self.add_course_button.setObjectName("add_course_button")

        self.select_course_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_course_button.setGeometry(QtCore.QRect(280, 370, 240, 40))
        self.select_course_button.setObjectName("select_course_button")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "选课管理系统 by WDZRMPCBIT"))
        self.add_college_button.setText(_translate("MainWindow", "添加院系"))
        self.add_teacher_button.setText(_translate("MainWindow", "添加教师"))
        self.add_student_button.setText(_translate("MainWindow", "添加学生"))
        self.add_course_button.setText(_translate("MainWindow", "新增课程"))
        self.select_course_button.setText(_translate("MainWindow", "选课"))
