# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, sqlite3
from PyQt5 import QtWidgets
from main_window import Ui_MainWindow
from add_college import Ui_AddCollegeWidget
from add_teacher import Ui_AddTeacherWidget
from add_student import Ui_AddStudentWidget
from add_course import Ui_AddCourseWidget
from select_course import Ui_SelectCourseWidget

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)

    main_window = QtWidgets.QMainWindow()
    main_ui = Ui_MainWindow()
    main_ui.setupUi(main_window)

    add_college_widget = QtWidgets.QWidget()
    add_college_ui = Ui_AddCollegeWidget()
    add_college_ui.setupUi(add_college_widget)
    main_ui.add_college_button.clicked.connect(add_college_widget.show)

    add_teacher_widget = QtWidgets.QWidget()
    add_teacher_ui = Ui_AddTeacherWidget()
    add_teacher_ui.setupUi(add_teacher_widget)
    main_ui.add_teacher_button.clicked.connect(add_teacher_widget.show)

    add_student_widget = QtWidgets.QWidget()
    add_student_ui = Ui_AddStudentWidget()
    add_student_ui.setupUi(add_student_widget)
    main_ui.add_student_button.clicked.connect(add_student_widget.show)

    add_course_widget = QtWidgets.QWidget()
    add_course_ui = Ui_AddCourseWidget()
    add_course_ui.setupUi(add_course_widget)
    main_ui.add_course_button.clicked.connect(add_course_widget.show)

    select_course_widget = QtWidgets.QWidget()
    select_course_ui = Ui_SelectCourseWidget()
    select_course_ui.setupUi(select_course_widget)
    main_ui.select_course_button.clicked.connect(select_course_widget.show)

    main_window.show()
    sys.exit(app.exec_())
