# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.add_college_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_college_button.setGeometry(QtCore.QRect(280, 50, 240, 40))
        self.add_college_button.setObjectName("add_college_button")
        self.add_college_button.clicked.connect(self._add_college)

        self.add_teacher_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_teacher_button.setGeometry(QtCore.QRect(280, 130, 240, 40))
        self.add_teacher_button.setObjectName("add_teacher_button")
        self.add_teacher_button.clicked.connect(self._add_teacher)

        self.add_student_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_student_button.setGeometry(QtCore.QRect(280, 210, 240, 40))
        self.add_student_button.setObjectName("add_student_button")
        self.add_student_button.clicked.connect(self._add_student)

        self.add_course_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_course_button.setGeometry(QtCore.QRect(280, 290, 240, 40))
        self.add_course_button.setObjectName("add_course_button")
        self.add_course_button.clicked.connect(self._add_course)

        self.select_course_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_course_button.setGeometry(QtCore.QRect(280, 370, 240, 40))
        self.select_course_button.setObjectName("select_course_button")
        self.select_course_button.clicked.connect(self._select_course)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "选课管理系统 by WDZRMPCBIT"))
        self.add_college_button.setText(_translate("MainWindow", "添加院系"))
        self.add_teacher_button.setText(_translate("MainWindow", "添加教师"))
        self.add_student_button.setText(_translate("MainWindow", "添加学生"))
        self.add_course_button.setText(_translate("MainWindow", "新增课程"))
        self.select_course_button.setText(_translate("MainWindow", "选课"))

    def _add_college(self):
        from add_college import Ui_AddCollegeWidget
        self._new_widget(Ui_AddCollegeWidget)

    def _add_teacher(self):
        from add_teacher import Ui_AddTeacherWidget
        self._new_widget(Ui_AddTeacherWidget)

    def _add_student(self):
        from add_student import Ui_AddStudentWidget
        self._new_widget(Ui_AddStudentWidget)

    def _add_course(self):
        from add_course import Ui_AddCourseWidget
        self._new_widget(Ui_AddCourseWidget)

    def _select_course(self):
        from select_course import Ui_SelectCourseWidget
        self._new_widget(Ui_SelectCourseWidget)

    def _new_widget(self, Widget):
        self._widget = QtWidgets.QWidget()
        ui = Widget()
        ui.setupUi(self._widget)
        self._widget.show()
