# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/select_course.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectCourseWidget(object):
    def setupUi(self, SelectCourseWidget):
        SelectCourseWidget.setObjectName("SelectCourseWidget")
        SelectCourseWidget.resize(800, 480)
        self.student_id_label = QtWidgets.QLabel(SelectCourseWidget)
        self.student_id_label.setGeometry(QtCore.QRect(160, 110, 240, 40))
        self.student_id_label.setObjectName("student_id_label")
        self.student_id_edit = QtWidgets.QLineEdit(SelectCourseWidget)
        self.student_id_edit.setGeometry(QtCore.QRect(400, 110, 240, 40))
        self.student_id_edit.setObjectName("student_id_edit")
        self.accept_button = QtWidgets.QPushButton(SelectCourseWidget)
        self.accept_button.setGeometry(QtCore.QRect(280, 280, 240, 40))
        self.accept_button.setObjectName("accept_button")
        self.course_box = QtWidgets.QComboBox(SelectCourseWidget)
        self.course_box.setGeometry(QtCore.QRect(400, 190, 240, 40))
        self.course_box.setObjectName("course_box")
        self.course_label = QtWidgets.QLabel(SelectCourseWidget)
        self.course_label.setGeometry(QtCore.QRect(160, 190, 240, 40))
        self.course_label.setObjectName("course_label")
        self.search_button = QtWidgets.QPushButton(SelectCourseWidget)
        self.search_button.setGeometry(QtCore.QRect(660, 110, 75, 40))
        self.search_button.setObjectName("search_button")

        self.retranslateUi(SelectCourseWidget)
        QtCore.QMetaObject.connectSlotsByName(SelectCourseWidget)

    def retranslateUi(self, SelectCourseWidget):
        _translate = QtCore.QCoreApplication.translate
        SelectCourseWidget.setWindowTitle(_translate("SelectCourseWidget", "选课"))
        self.student_id_label.setText(_translate("SelectCourseWidget", "学号"))
        self.accept_button.setText(_translate("SelectCourseWidget", "选课"))
        self.course_label.setText(_translate("SelectCourseWidget", "候选课程"))
        self.search_button.setText(_translate("SelectCourseWidget", "查询"))
